### ISSUE TITLE
Could partnr multi-agent setting used for multiple robot agents with NO human agent?

### ISSUE THREAD

**Issue by leihamilton** [facebookresearch/partnr-planner#19]
Thanks for the hard work! I was able to run examples.

I would like to try the multi-agent setting used for multiple robot agents (>=2) with NO human agent, is this one of the use cases of partnr? Thanks.

**Comment by xavierpuigf** [comment]
Hi! The current task should support two robots with no human with relatively low code changes, mostly config changes. For more than 2 robots, while habitat-sim enables this there are a few parts in the partnr code where we assume at most two agents. 

Other than `EnvironmentInterface`, `world_graph.py` assumes that one of the agents is a human. You should probably change the logic in update so that it checks which agent is grabbing which object independently of the object type. Happy to help resolve issues if you see bugs after making the changes.

**Comment by leihamilton** [comment]
@xavierpuigf Thanks for your quick response, really appreciate it. Will give it a try.

**Comment by MattBortoletto** [comment]
Hi! I have a follow up question @xavierpuigf : is it feasible to extend PARTNR to 3 agents (one robot and two humans)? 

> there are a few parts in the partnr code where we assume at most two agents.

Could you please point to these parts of the code? 

Thank you in advance!

**Comment by HoBeom** [comment]
Hi @MattBortoletto, I'm also working on extending PARTNR for multiple agents. Initially, I tried using two human agents and observed that the humans overlap in the simulator. It seems necessary to adjust the scenario initialization logic, specifically the agent positioning when changing agent types. Additionally, for cases involving three or more agents, you might need to explicitly define the initial positions for each agent in the dataset.

**Comment by xavierpuigf** [comment]
How are you making this update? This looks like the same action is updating both agents at the same time. Each agent should have their own actions.

**Comment by HoBeom** [comment]
I'm currently focusing on reproducing the baseline performance, so I've temporarily paused the multi-agent implementation. I noticed that when running more than two simulator at the same time, the process crashes—this might be due to insufficient RAM on my system. Once the baseline reproduction is complete, I'll resume testing the agent type setting.

For reference, the test video I shared earlier was from a decentralized setting where I modified a part of the planner_multi_agent_demo_config.yaml. Below is the configureation I used:

```
defaults:
  - /training@             : base_train
  - /habitat_conf          : oracle_spot_kinematic_multi_agent
  - /habitat_conf/task     : rearrange_easy_multi_agent
  - /evaluation: centralized_evaluation_runner_multi_agent
  - /habitat/simulator/agents@habitat.simulator.agents.agent_0: human
  - /habitat/task/actions@habitat.task.actions.agent_0_humanoid_base_velocity: humanoid_base_velocity
  - /habitat/task/actions@habitat.task.actions.agent_0_humanoidjoint_action: humanoidjoint_action
  - /habitat/simulator/agents@habitat.simulator.agents.agent_1: human
  - /habitat/task/actions@habitat.task.actions.agent_1_humanoid_base_velocity: humanoid_base_velocity
  - /habitat/task/actions@habitat.task.actions.agent_1_humanoidjoint_action: humanoidjoint_action
  - /world_model@world_model: gt_graph
  - /trajectory@trajectory : trajectory_logger
  - /agent/@agents.agent_0.config: oracle_rearrange_object_states_agent
  - /agent/@agents.agent_1.config: oracle_rearrange_object_states_agent

... (other settings remain unchanged) ... 

habitat:
  task:
    pddl_domain_def: fp
  simulator:
    agents:
      agent_0:
        radius: 0.3
        articulated_agent_type: 'KinematicHumanoid'
        articulated_agent_urdf: 'data/humanoids/humanoid_data/male_0/male_0.urdf'
        motion_data_path: "data/humanoids/humanoid_data/male_0/male_0_motion_data_smplx.pkl"
      agent_1:
        radius: 0.3
        articulated_agent_type: 'KinematicHumanoid'
        articulated_agent_urdf: 'data/humanoids/humanoid_data/female_2/female_2.urdf'
        motion_data_path: "data/humanoids/humanoid_data/female_2/female_2_motion_data_smplx.pkl"
```
Could you please point out which parts of the code should be modified to allow free configuration of the agent type? That would be a great help.
